### ISSUE TITLE
Domain is now sale!!!

### ISSUE THREAD

**Issue by opcahf** [BitcoinPlatinum/BitcoinPlatinum#12]
https://opcahf.github.io/

**Comment by Hypeouseaus** [comment]
ㅋㅋ 진짜 막 나가네 씨발 새끼들

**Comment by Hypeouseaus** [comment]
야 이거 클로즈 안하냐? ㅋㅋ 딱 봐도 지 부계정이겠지만

**Comment by hackmod** [comment]
아직도 이 사이트나 비트코인 다이아몬드를 믿고 계시는 사용자분들 없겠지만,
트위터에만 프로젝트 변명 쓰지 마시고, 프로젝트 참여자분들은 최소 이슈 관리좀 하시기 바랍니다.
그래야 진짜로 진행중인 프로젝트인지, 나가리된 프로젝트인지 알것 아니겠습니까?

I guess no one still believes in this site or Bitcoin Diamond,
Do not write a project excuse only on Twitter.
Do minimum issue management on this issue. please.
