### ISSUE TITLE
MiningPool

### ISSUE THREAD

**Issue by BRyanC0701** [BitcoinPlatinum/BitcoinPlatinum#7]
Can I create a mining pool now???

**Comment by BRyanC0701** [comment]
Is the Coin Node same as Coin Daemon???

**Comment by wjcloud** [comment]
@BRyanC0701 Hello! Yes you can create the mining pool for BTP. You can refer the z-nomp source code for BTP here https://github.com/BitcoinPlatinum/BitcoinPlatinum
